"""Operational energy engine.

Primary path: build an IDF from the building parameters and run a real
EnergyPlus simulation (`energyplus` CLI, installed in the Docker image),
then read end-use totals from the tabular CSV output.

Fallback path: a deterministic ISO 13790-style monthly quasi-steady-state
model, so the dashboard always has heating / cooling / lighting numbers.
"""
from __future__ import annotations

import csv
import math
import os
import shutil
import subprocess
import tempfile
from typing import Any

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# climate zone -> (heating degree days, cooling degree days, avg daily solar kWh/m2)
CLIMATES: dict[str, tuple[float, float, float]] = {
    "arctic": (6000, 50, 1.8),
    "cold": (4200, 300, 2.6),
    "temperate": (2400, 700, 3.2),
    "mediterranean": (1400, 1200, 4.4),
    "hot-dry": (600, 2600, 5.6),
    "hot-humid": (300, 3000, 4.8),
    "tropical": (100, 3200, 4.9),
}

# building type -> (lighting W/m2, equipment W/m2, operating hours per year)
BUILDING_TYPES: dict[str, tuple[float, float, float]] = {
    "office": (9.0, 12.0, 2600),
    "residential": (5.0, 6.0, 5200),
    "retail": (14.0, 8.0, 3600),
    "school": (10.0, 7.0, 2000),
    "hospital": (12.0, 20.0, 8760),
    "industrial": (8.0, 25.0, 4000),
}

DEFAULT_GRID_FACTOR = 0.233  # kgCO2e / kWh


def _profile(climate_zone: str | None, building_type: str | None):
    cz = (climate_zone or "temperate").strip().lower()
    bt = (building_type or "office").strip().lower()
    return CLIMATES.get(cz, CLIMATES["temperate"]), BUILDING_TYPES.get(bt, BUILDING_TYPES["office"])


def energyplus_available() -> bool:
    return shutil.which("energyplus") is not None


def build_idf(floor_area, num_floors, u_wall, u_roof, u_window, wwr,
              lighting_w_m2, equipment_w_m2, heating_setpoint, cooling_setpoint) -> str:
    """Minimal shoebox IDF driven by the BIM/building parameters."""
    side = max(4.0, math.sqrt(max(floor_area, 1.0) / max(num_floors, 1)))
    height = 3.0 * max(num_floors, 1)
    return f"""! Auto-generated by BIM Sustainability Analyzer
Version, 23.2;
Building, BIMModel, 0.0, City, 0.04, 0.4, FullExterior, 25, 6;
Timestep, 4;
GlobalGeometryRules, UpperLeftCorner, CounterClockWise, World;
SimulationControl, No, No, No, Yes, Yes;
RunPeriod, Annual, 1, 1, , 12, 31, , , , , , Yes;
ScheduleTypeLimits, Any Number;
Schedule:Constant, Always, Any Number, 1.0;

Material:NoMass, WallR, Rough, {max(0.05, 1.0 / max(u_wall, 0.05)):.3f}, 0.9, 0.7, 0.7;
Material:NoMass, RoofR, Rough, {max(0.05, 1.0 / max(u_roof, 0.05)):.3f}, 0.9, 0.7, 0.7;
Construction, ExtWall, WallR;
Construction, ExtRoof, RoofR;
WindowMaterial:SimpleGlazingSystem, Glz, {u_window:.2f}, 0.4, 0.7;
Construction, ExtWindow, Glz;

Zone, Block, 0, 0, 0, 0, , 1, , {height:.2f};
BuildingSurface:Detailed, Floor, Floor, ExtWall, Block, Ground, , NoSun, NoWind, 0, 4,
  0,0,0, {side:.2f},0,0, {side:.2f},{side:.2f},0, 0,{side:.2f},0;
BuildingSurface:Detailed, Roof, Roof, ExtRoof, Block, Outdoors, , SunExposed, WindExposed, 0, 4,
  0,{side:.2f},{height:.2f}, {side:.2f},{side:.2f},{height:.2f}, {side:.2f},0,{height:.2f}, 0,0,{height:.2f};

ZoneInfiltration:DesignFlowRate, Inf, Block, Always, Flow/Area, , , 0.0003, , 1, 0, 0, 0;
Lights, Lgt, Block, Always, Watts/Area, , {lighting_w_m2:.2f}, , 0, 0.2, 0.6;
ElectricEquipment, Eqp, Block, Always, Watts/Area, , {equipment_w_m2:.2f}, , 0, 0, 0.5;
HVACTemplate:Thermostat, Stat, , {heating_setpoint:.1f}, , {cooling_setpoint:.1f};
HVACTemplate:Zone:IdealLoadsAirSystem, Block, Stat;

Output:Table:SummaryReports, AnnualBuildingUtilityPerformanceSummary;
OutputControl:Table:Style, CommaAndHTML;
! window-to-wall ratio used by the generator: {wwr:.2f}
"""


def _is_num(value: str) -> bool:
    try:
        float(value)
        return True
    except Exception:
        return False


def _run_energyplus(idf: str, weather_file: str | None) -> dict[str, float] | None:
    if not energyplus_available():
        return None
    workdir = tempfile.mkdtemp(prefix="eplus-")
    idf_path = os.path.join(workdir, "in.idf")
    with open(idf_path, "w") as fh:
        fh.write(idf)
    cmd = ["energyplus", "-d", workdir, "-r"]
    if weather_file and os.path.exists(weather_file):
        cmd += ["-w", weather_file]
    cmd.append(idf_path)
    try:
        subprocess.run(cmd, cwd=workdir, capture_output=True, timeout=900, check=False)
        table = os.path.join(workdir, "eplustbl.csv")
        if not os.path.exists(table):
            return None
        heating = cooling = lighting = equipment = 0.0
        with open(table, newline="", errors="ignore") as fh:
            for row in csv.reader(fh):
                if not row:
                    continue
                label = (row[0] or "").strip().lower()
                nums = [float(c) for c in row[1:] if _is_num(c)]
                if not nums:
                    continue
                total = sum(nums)
                if label.startswith("heating"):
                    heating = max(heating, total)
                elif label.startswith("cooling"):
                    cooling = max(cooling, total)
                elif label.startswith("interior lighting"):
                    lighting = max(lighting, total)
                elif label.startswith("interior equipment"):
                    equipment = max(equipment, total)
        if heating + cooling + lighting <= 0:
            return None
        # eplustbl end-use totals are in GJ -> kWh
        return {
            "heating_kwh": heating * 277.778,
            "cooling_kwh": cooling * 277.778,
            "lighting_kwh": lighting * 277.778,
            "equipment_kwh": equipment * 277.778,
        }
    except Exception:
        return None
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _iso13790(floor_area, num_floors, climate, building, u_wall, u_roof, u_window,
              wwr, infiltration_ach, hvac_cop, heating_efficiency, lpd) -> dict[str, Any]:
    hdd, cdd, solar = climate
    _lpd, epd, hours = building
    lpd = lpd or _lpd

    side = math.sqrt(max(floor_area, 1.0) / max(num_floors, 1))
    height = 3.0 * max(num_floors, 1)
    wall_area = 4 * side * height
    window_area = wall_area * wwr
    opaque_wall = max(wall_area - window_area, 0.0)
    roof_area = floor_area / max(num_floors, 1)

    h_trans = opaque_wall * u_wall + roof_area * u_roof + window_area * u_window   # W/K
    h_vent = 0.33 * infiltration_ach * (floor_area * 3.0)
    h_total = h_trans + h_vent

    internal_gain = (lpd + epd) * floor_area * hours / 1000.0        # kWh/yr
    # g-value x shading x orientation exposure for the whole envelope
    solar_gain = window_area * solar * 365 * 0.4 * 0.7 * 0.35        # kWh/yr
    gains = internal_gain + solar_gain

    heat_loss = h_total * hdd * 24 / 1000.0                          # kWh/yr
    # ISO 13790 monthly gain utilisation factor (a = 5 for medium inertia)
    gamma = gains / heat_loss if heat_loss > 0 else 999.0
    if abs(gamma - 1.0) < 1e-6:
        eta = 5 / 6
    else:
        eta = (1 - gamma ** 5) / (1 - gamma ** 6)
    heating_demand = max(heat_loss - eta * gains, 0.0)
    # cooling: envelope gains over CDD plus the share of internal/solar gains
    # that cannot be dissipated by losses
    cooling_demand = max(h_total * cdd * 24 / 1000.0 + 0.5 * gains * (1 - eta * 0.5), 0.0)

    heating = heating_demand / max(heating_efficiency, 0.1)
    cooling = cooling_demand / max(hvac_cop, 0.5)
    lighting = lpd * floor_area * hours / 1000.0
    equipment = epd * floor_area * hours / 1000.0

    heat_w, cool_w = [], []
    for i in range(12):
        phase = math.cos(i / 12 * 2 * math.pi)
        heat_w.append(max(phase, 0.0) ** 1.2 + 0.03)
        cool_w.append(max(-phase, 0.0) ** 1.2 + 0.03)
    hs, cs = sum(heat_w), sum(cool_w)
    monthly = [
        {
            "month": MONTHS[i],
            "heating": round(heating * heat_w[i] / hs, 1),
            "cooling": round(cooling * cool_w[i] / cs, 1),
            "lighting": round(lighting / 12, 1),
        }
        for i in range(12)
    ]
    return {
        "heating_kwh": heating, "cooling_kwh": cooling,
        "lighting_kwh": lighting, "equipment_kwh": equipment, "monthly": monthly,
    }


def simulate(
    *,
    floor_area: float | None,
    num_floors: int | None,
    building_type: str | None,
    climate_zone: str | None,
    u_wall: float = 0.30,
    u_roof: float = 0.20,
    u_window: float = 1.60,
    wwr: float = 0.35,
    infiltration_ach: float = 0.45,
    hvac_cop: float = 3.2,
    heating_efficiency: float = 0.92,
    lighting_power_density: float | None = None,
    grid_carbon_factor: float = DEFAULT_GRID_FACTOR,
    weather_file: str | None = None,
) -> dict[str, Any]:
    area = float(floor_area or 1000.0)
    floors = int(num_floors or 1)
    climate, building = _profile(climate_zone, building_type)
    lpd = lighting_power_density or building[0]

    inputs = {
        "floor_area": area, "num_floors": floors, "building_type": building_type,
        "climate_zone": climate_zone, "u_wall": u_wall, "u_roof": u_roof,
        "u_window": u_window, "wwr": wwr, "infiltration_ach": infiltration_ach,
        "hvac_cop": hvac_cop, "heating_efficiency": heating_efficiency,
        "lighting_power_density": lpd, "grid_carbon_factor": grid_carbon_factor,
    }

    fallback = _iso13790(area, floors, climate, building, u_wall, u_roof, u_window,
                         wwr, infiltration_ach, hvac_cop, heating_efficiency, lpd)

    engine = "iso13790-fallback"
    result = fallback
    eplus = _run_energyplus(
        build_idf(area, floors, u_wall, u_roof, u_window, wwr, lpd, building[1], 20.0, 24.0),
        weather_file or os.environ.get("EPW_FILE"),
    )
    if eplus:
        engine = "energyplus"
        hs = sum(m["heating"] for m in fallback["monthly"]) or 1
        cs = sum(m["cooling"] for m in fallback["monthly"]) or 1
        monthly = [
            {
                "month": m["month"],
                "heating": round(eplus["heating_kwh"] * m["heating"] / hs, 1),
                "cooling": round(eplus["cooling_kwh"] * m["cooling"] / cs, 1),
                "lighting": round(eplus["lighting_kwh"] / 12, 1),
            }
            for m in fallback["monthly"]
        ]
        result = {**eplus, "monthly": monthly}

    total = (result["heating_kwh"] + result["cooling_kwh"]
             + result["lighting_kwh"] + result["equipment_kwh"])
    return {
        "engine": engine,
        "heating_kwh": round(result["heating_kwh"], 1),
        "cooling_kwh": round(result["cooling_kwh"], 1),
        "lighting_kwh": round(result["lighting_kwh"], 1),
        "equipment_kwh": round(result["equipment_kwh"], 1),
        "total_kwh": round(total, 1),
        "eui_kwh_m2": round(total / max(area, 1.0), 2),
        "operational_carbon_kg": round(total * grid_carbon_factor, 1),
        "grid_factor_kg_kwh": grid_carbon_factor,
        "monthly_json": result["monthly"],
        "inputs_json": inputs,
    }
