"""Initial migration

Revision ID: 55f79ef16403
Revises: 
Create Date: 2026-09-05 20:32:30.368117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f79ef16403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('embodied_carbon', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('building_type', sa.String(length=60), nullable=True),
    sa.Column('climate_zone', sa.String(length=60), nullable=True),
    sa.Column('floor_area', sa.Float(), nullable=True),
    sa.Column('num_floors', sa.Integer(), nullable=True),
    sa.Column('ifc_url', sa.String(length=500), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.String(length=30), nullable=True),
    sa.Column('parse_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('elements',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('global_id', sa.String(length=64), nullable=True),
    sa.Column('ifc_type', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('storey', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('embodied_carbon_kg', sa.Float(), nullable=True),
    sa.Column('properties_json', sa.JSON(), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_global_id'), 'elements', ['global_id'], unique=False)
    op.create_index(op.f('ix_elements_project_id'), 'elements', ['project_id'], unique=False)
    op.create_table('energy_results',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=40), nullable=True),
    sa.Column('heating_kwh', sa.Float(), nullable=True),
    sa.Column('cooling_kwh', sa.Float(), nullable=True),
    sa.Column('lighting_kwh', sa.Float(), nullable=True),
    sa.Column('equipment_kwh', sa.Float(), nullable=True),
    sa.Column('total_kwh', sa.Float(), nullable=True),
    sa.Column('eui_kwh_m2', sa.Float(), nullable=True),
    sa.Column('operational_carbon_kg', sa.Float(), nullable=True),
    sa.Column('grid_factor_kg_kwh', sa.Float(), nullable=True),
    sa.Column('monthly_json', sa.JSON(), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_results_project_id'), 'energy_results', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_results_project_id'), table_name='energy_results')
    op.drop_table('energy_results')
    op.drop_index(op.f('ix_elements_project_id'), table_name='elements')
    op.drop_index(op.f('ix_elements_global_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('materials')
    # ### end Alembic commands ###
