"""Add Source Column to Materials

Revision ID: 2e20975961e2
Revises: 55f79ef16403
Create Date: 2026-09-10 22:06:17.137833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e20975961e2'
down_revision: Union[str, None] = '55f79ef16403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('source', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'source')
    # ### end Alembic commands ###
